version: '3.9'

services:
  backend:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: backend
      ports:
        - "3000:3000"
      environment:
        - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase?schema=public
      depends_on:
        - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge